# Generated by Django 4.2.7 on 2024-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(default='23098', max_length=10),
        ),
    ]
