# Generated by Django 4.2.7 on 2024-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0002_user_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(max_length=10),
        ),
    ]
