# Generated by Django 4.2.7 on 2024-04-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0003_alter_user_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
