# Generated by Django 4.2.7 on 2024-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0005_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user_provider',
            field=models.CharField(default='email', max_length=300),
        ),
    ]
