# Generated by Django 4.2.7 on 2024-05-30 15:10

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0006_user_auth_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=22, max_length=200, prefix='usr-', primary_key=True, serialize=False, unique=True),
        ),
    ]
