# Generated by Django 4.2.7 on 2024-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='olisa', max_length=150),
        ),
    ]
